### PR TITLE
Gnome 40 fixes

### LINKED ISSUE #53: Settings failure under gnome 40
Try to configure the plugin gives the following error:

> The settings of extension TeaTime@oleid.mescharet.de had an error:
> ```
> Error: No property margin on Gjs_TeaTimePrefsWidget
> ```
> 
> Stack trace:
> ```
> _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
> _init@/usr/share/gnome-shell/extensions/TeaTime@oleid.mescharet.de/prefs.js:28:9
> buildPrefsWidget@/usr/share/gnome-shell/extensions/TeaTime@oleid.mescharet.de/prefs.js:294:15
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> start@resource:///org/gnome/gjs/modules/script/package.js:190:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
>

### PR DESCRIPTION
**Pull request by zeners**
replace Toolbar, FileSelector (Soundfile) and Grid.margin-property

fixes #53

### CODE REVIEW

**Comment by oleid** [comment]
Thanks for the pull request! 

Do you happen to know if this will also work on gnome < 40?

**Comment by zeners** [comment]
i testet it with 3.36.6 and i get an error on settings, so curently not

**Comment by zeners** [comment]
compatibility restored

**Comment by oleid** [comment]
Thank you very much! :)

**Pull request merged**
