### PR TITLE
Gnome Shell 45

### PR DESCRIPTION
**Pull request by zeners**
solves #63 made by @jwrdegoede

### CODE REVIEW

**Comment by jwrdegoede** [comment]
Thanks, I was planning on submitting a pull-req for this myself but did not get around to it yet.

Note that this is different then the gnome-shell 40-44 compatibility changes though. Those kept compatibility with older gnome-shell versions. Where as the changes in gnome-shell 45 are such that adding support for it breaks support for older versions.

**Comment by jwrdegoede** [comment]
@zeners it seems that @oleid is no longer actively maintaining it and that the 2 of us are keeping it alive atm. So I think one of us should apply to take over the extension on https://extensions.gnome.org/ and TBH I'm sorta hoping you (@zeners) can take it over there since I'm generally speaking very busy with my upstream kernel work.

@oleid would you be willing to give @zeners access to teatime at https://extensions.gnome.org/  ?  (I think that handing it over there is probably the easiest way)

**Comment by zeners** [comment]
Currently i don't have accounts on https://extensions.gnome.org or https://aur.archlinux.org, which should also adopted (on aur, it's open to adopt). On extensions.gnome.org it should be possible to make a copy as another author. 

Give me some time, to think about.

**Comment by zeners** [comment]
AUR adopted: new version-numbering introduced -> downgrade required

currently Major (45) will be released, when i know how to deploy to extensions.gnome.org

**Comment by zeners** [comment]
new versions will hopefully be listed under https://extensions.gnome.org/accounts/profile/zeners

**Comment by jwrdegoede** [comment]
Great, thank you for taking care of this!

**Comment by zeners** [comment]
still waiting for review: https://extensions.gnome.org/review/

**Comment by jwrdegoede** [comment]
> @jwrdegoede @oleid i have to rename the extension or takeover oleid's account on extensions.gnome.org
> 
> https://extensions.gnome.org/review/48013#previous_reviews

Right, this is why I wrote the following above:

"@oleid would you be willing to give @zeners access to teatime at https://extensions.gnome.org/ ? (I think that handing it over there is probably the easiest way)"

@oleid I have asked how to transfer the extensio on the extensions channel on GNOME's matrix instance and there I got the following answer: "Since that's the only extension they have in their profile, you can ask them to change their email and username to your email and username." 

If @zeners sends you a private message with his info, would you be willing to make this change?

**Comment by jwrdegoede** [comment]
@oleid you should be able to make those changes here: https://extensions.gnome.org/accounts/settings

**Comment by zeners** [comment]
@jwrdegoede thanks for asking at matrix. I don't know, if or when this takeover will happen. In the meantime i will publish it under a new (hopefully temporary) name TeaTimer. I don't like to see it offline for a unpredictable time.

**Comment by zeners** [comment]
@oleid EGO-Profil: [Zeners](https://extensions.gnome.org/accounts/profile/Zeners)

**Comment by jwrdegoede** [comment]
> @jwrdegoede thanks for asking at matrix. I don't know, if or when this takeover will happen. In the meantime i will publish it under a new (hopefully temporary) name TeaTimer. I don't like to see it offline for a unpredictable time.

Ok, that sounds good to me, thank you for working on this.

**Pull request closed without merging**
