### PR TITLE
remember running Timer

### LINKED ISSUE #14: Countdown stops, if shell is locked
Note to myself: This seems to work for the pomodoro guys, check how they do it!

### PR DESCRIPTION
**Pull request by zeners**
fixed #14 

also updated metadata with gnome version 40 and running js-beautify

### CODE REVIEW

**Comment by zeners** [comment]
added remaining time to stop menu item, if graphical style is in use

**Comment by zeners** [comment]
is something wrong with it?

**Comment by oleid** [comment]
> is something wrong with it?

Oh, I'm very sorry, I missed the notification mail for your pull request.

No, the changes seem fine.

On first glance:

* There seems to be a huge whitespace diff in the javascript code. Maybe my old beautify-code script could help? Or do you know something that gives reproducible code formatting for JavaScript? I'm not really a JS person.
* I'm wondering if remember_running_timer needs to be configurable? Isn't that something everybody would want in any case?

**Comment by zeners** [comment]
https://github.com/oleid/gnome-shell-teatime/issues/14#issuecomment-373932398 Korbi requested it, i think

**Comment by oleid** [comment]
> [#14 (comment)](https://github.com/oleid/gnome-shell-teatime/issues/14#issuecomment-373932398) Korbi requested it, i think
> 
> i called the beautify-script, which whitespace-diff you mean?

In src/extension.js especially. When you have a look at the diff of that file in this pull request, you notice that is is quite big. If you, however, make github ignore the whitespace diff, the change is quite small. I figured, there are lots of changes.

I think I used this one back then: https://packages.debian.org/sid/jsbeautifier

But it would seem there is now also a similar named tool based on nodejs with different output :roll_eyes: 
I'll check if I can tweak the settings.

**Comment by zeners** [comment]
removing the option is not a big deal

**Comment by oleid** [comment]
It would seem that the beautifier output simply changed over time and both, the python and the original one yield the same output. I fixed that on the master branch, however, this caused conflicts. I fixed them in github's web interface.

**Comment by oleid** [comment]
Thanks a lot! :)

**Pull request merged**
