### PR TITLE
Add compatibility with GNOME 3.34 and GNOME 3.36

### PR DESCRIPTION
**Pull request by jwrdegoede**
The changes in this pull-req make TeaTime compatible with GNOME 3.34 and GNOME-3.36.

Note since there were quite a few changes all over the javascrips API these changes break compatibility with older GNOME shell versions, so you may wish to use a separate branch for this.

### CODE REVIEW

**Comment by StefanFabian** [comment]
@oleid Could you please merge this and update the extension in the gnome extensions hub?

or alternatively, maybe @jwrdegoede could you distribute your fork in the extensions hub?
This extension seems pretty cool but it's now slowly dying since it isn't working on any recent distribution.

**Comment by blackjackshellac** [comment]
FWIW, I'm not sure that my [Kitchen Timer](https://github.com/blackjackshellac/kitchenTimer) extension works with 3.34 but I do have it working on 3.36 and 3.38.  It's also on [extensions.gnome.org](https://extensions.gnome.org/extension/3955/kitchen-timer/)

**Comment by jwrdegoede** [comment]
> @oleid Could you please merge this and update the extension in the gnome extensions hub?
> 
> or alternatively, maybe @jwrdegoede could you distribute your fork in the extensions hub?
> This extension seems pretty cool but it's now slowly dying since it isn't working on any recent distribution.

I wouldn't mind my fork becoming the official teatime version on the gnome extensions hub. But I'm mainly an upstream kernel developer and almost all my time goes there.

From my pov, ideally someone else would step up to create an account at the gnome-extension hub, tag a release, upload it there, etc. I'm happy to help with fixing the extension if things break again. But I really don't have time for the day to day admin stuff, such as e.g. answering user (support) questions, etc...

With that said if someone is willing to step up to do this, then ideally @oleid would hand over the existing gnome-extension website/hub entry maintainership to that new person, rather then that we create a new competing teatime extension at the hub.

**Comment by oleid** [comment]
> 
> With that said if someone is willing to step up to do this, then ideally @oleid would hand over the existing gnome-extension website/hub entry maintainership to that new person, rather then that we create a new competing teatime extension at the hub.

I'll gladly hand over maintainership if someone wants to step up. I didn't find the time to work on this for some time now. And on top of that, I'm not using Gnome at the moment.

**Comment by oleid** [comment]
Uploaded a new version to extensions.gnome.org, currently in review.

**Comment by jwrdegoede** [comment]
> Uploaded a new version to extensions.gnome.org, currently in review.

That is great, thank you!

**Pull request merged**
